### ISSUE TITLE
BE: Research Go/Testing

### ISSUE THREAD

**Issue by meghanstovall** [learn-able/learnable-be#4]
Resource:
https://github.com/go-pg

https://www.youtube.com/playlist?list=PLmxT2pVYo5LDMV0epL4z4CUbxvIw6umg_

https://quii.gitbook.io/learn-go-with-tests/

**Comment by alerrian** [comment]
[Learn Go With Tests](https://quii.gitbook.io/learn-go-with-tests/)
This resource, and specifically the section on HTTP, is incredible for learning best practice TDD for Go. Getting through the main pieces of it will help learn a lot of great stuff related to go and how to test it.

**Comment by alerrian** [comment]
https://github.com/gin-gonic/gin#quick-start
https://github.com/go-pg/docs/blob/master/guide/queries.md

These links have proven helpful for getting some of the http requests and the tests out of the way. Along with Go's own `httptest` package.
